# Generated by Django 2.2 on 2022-11-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(default='images/none/noimg.jpg', upload_to='images')),
                ('Rating', models.FloatField()),
                ('Description', models.CharField(max_length=500)),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
    ]
